---
apiVersion: v1
kind: Service
metadata:
  name: actual
  namespace: default
  labels:
    app.kubernetes.io/name: actual
    app.kubernetes.io/instance: actual
  annotations:
    tailscale.com/expose: "true"
    tailscale.com/hostname: "actual"
    tailscale.com/tags: "tag:http"
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: http
      protocol: TCP
      name: actual
  selector:
    app.kubernetes.io/name: actual
    app.kubernetes.io/instance: actual
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: actual-data
  namespace: default
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      storage: 10Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: actual
  namespace: default
  labels:
    app.kubernetes.io/name: actual
    app.kubernetes.io/instance: actual
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: actual
      app.kubernetes.io/instance: actual
  template:
    metadata:
      labels:
        app.kubernetes.io/name: actual
        app.kubernetes.io/instance: actual
    spec:
      securityContext:
        {}
      containers:
        - name: actual
          image: "docker.io/actualbudget/actual-server:25.2.1-alpine"
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 5006
              protocol: TCP
          resources:
            {}
          volumeMounts:
            - name: datadir
              mountPath: /data
          livenessProbe:
            exec:
              command:
                - node
                - /app/src/scripts/health-check.js
            initialDelaySeconds: 15
            periodSeconds: 20
      volumes:
        - name: datadir
          persistentVolumeClaim:
            claimName: actual-data
