---
kind: ConfigMap
metadata:
  name: coredns
  namespace: kube-system
apiVersion: v1
data:
  Corefile: |
    .:53 {
        errors
        health
        ready
        kubernetes cluster.local in-addr.arpa ip6.arpa {
          pods insecure
          fallthrough in-addr.arpa ip6.arpa
        }
        hosts /etc/coredns/NodeHosts {
          ttl 60
          reload 15s
          fallthrough
        }
        prometheus :9153
        forward . 45.90.28.89:53
        cache 30
        loop
        reload
        loadbalance

        forward barn-banana.ts.net 10.43.0.15 100.100.100.100 {
            policy sequential
            health_check 5s
            max_fails 2
            expire 10s
        }
    }

  NodeHosts: |
    192.168.1.22 homelab
