---
kind: ConfigMap
metadata:
  name: coredns
  namespace: kube-system
apiVersion: v1
data:
  Corefile: |
    .:53 {
        errors
        health
        ready
        kubernetes cluster.local in-addr.arpa ip6.arpa {
          pods insecure
          fallthrough in-addr.arpa ip6.arpa
        }
        hosts /etc/coredns/NodeHosts {
          ttl 60
          reload 15s
          fallthrough
        }
        prometheus :9153
        forward . 45.90.28.89:53
        cache 30
        loop
        reload
        loadbalance
    }
    barn-banana.ts.net:53 {
        forward . 100.100.100.100
    }
  NodeHosts: |
    192.168.1.22 nix-nvidia
---
# Service to expose Tailnet DNS IP to cluster
# Enabled by tailscale operator
apiVersion: v1
kind: Service
metadata:
  annotations:
    tailscale.com/tailnet-ip: 100.100.100.100
  name: tailnet-dns
  namespace: kube-system
spec:
  externalName: placeholder   # any value - will be overwritten by operator
  type: ExternalName
#---
#apiVersion: v1
#kind: ConfigMap
#metadata:
#  name: coredns-custom # has to be named this
#  namespace: kube-system
#data:
#  barn-banana.ts.net.server: |
#    barn-banana.ts.net {
#      forward . 100.100.100.100
#    }
