---
apiVersion: elasticsearch.k8s.elastic.co/v1
kind: Elasticsearch
metadata:
  name: elasticsearch
  namespace: monitoring
spec:
  version: 8.17.5
  nodeSets:
  - name: default
    count: 1
    podTemplate:
      spec:
        containers:
        - name: elasticsearch
          resources:
            requests:
              memory: 2Gi
              cpu: 4
            limits:
              memory: 2Gi
        volumes:
          - name: elasticsearch-data
            hostPath:
              path: /media/data-ssd/elastic/elasticsearch/data
              type: DirectoryOrCreate
          - name: elasticsearch-logs
            hostPath:
              path: /media/data-ssd/elastic/elasticsearch/logs
              type: DirectoryOrCreate
    config:
      node.store.allow_mmap: false
  http:
    tls:
      selfSignedCertificate:
        disabled: true
    service:
      metadata:
        annotations:
          tailscale.com/expose: "true"
          tailscale.com/hostname: "elasticsearch"
          tailscale.com/tags: "tag:elasticsearch"
---
apiVersion: kibana.k8s.elastic.co/v1
kind: Kibana
metadata:
  name: kibana
  namespace: monitoring
spec:
  version: 8.17.5
  count: 1
  http:
    tls:
      selfSignedCertificate:
        disabled: true
    service:
      metadata:
        annotations:
          tailscale.com/expose: "true"
          tailscale.com/hostname: "kibana"
          tailscale.com/tags: "tag:kibana"
  elasticsearchRef:
    name: elasticsearch
---
apiVersion: logstash.k8s.elastic.co/v1alpha1
kind: Logstash
metadata:
  name: logstash
  namespace: monitoring
spec:
  count: 1
  elasticsearchRefs:
    - name: elasticsearch
      clusterName: elasticsearch
  version: 8.17.5
  pipelines:
    - pipeline.id: main
      config.string: |
        input {
          beats {
            port => 5044
          }
        }
        output {
          elasticsearch {
            hosts => [ "elasticsearch.monitoring.svc.cluster.local" ]
          }
        }
  services:
    - name: beats
      service:
        metadata:
          annotations:
            tailscale.com/expose: "true"
            tailscale.com/hostname: "logstash"
            tailscale.com/tags: "tag:logstash"
        spec:
          type: ClusterIP
          ports:
            - port: 5044
              name: "beats"
              protocol: TCP
              targetPort: 5044
---
apiVersion: beat.k8s.elastic.co/v1beta1
kind: Beat
metadata:
  name: filebeat-k8s
  namespace: monitoring
spec:
  type: filebeat
  version: 8.17.5
  elasticsearchRef:
    name: elasticsearch
  kibanaRef:
    name: kibana
  config:
    filebeat:
      autodiscover:
        providers:
        - type: kubernetes
          node: ${NODE_NAME}
          hints:
            enabled: true
            default_config:
              type: container
              paths:
              - /var/log/containers/*${data.kubernetes.container.id}.log
    processors:
    - add_cloud_metadata: {}
    - add_host_metadata: {}
  daemonSet:
    podTemplate:
      spec:
        serviceAccountName: filebeat
        automountServiceAccountToken: true
        terminationGracePeriodSeconds: 30
        dnsPolicy: ClusterFirstWithHostNet
        hostNetwork: true # Allows to provide richer host metadata
        containers:
        - name: filebeat
          securityContext:
            runAsUser: 0
            # If using Red Hat OpenShift uncomment this:
            #privileged: true
          volumeMounts:
          - name: varlogcontainers
            mountPath: /var/log/containers
          - name: varlogpods
            mountPath: /var/log/pods
          - name: varlibdockercontainers
            mountPath: /var/lib/docker/containers
          env:
            - name: NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
        volumes:
        - name: varlogcontainers
          hostPath:
            path: /var/log/containers
        - name: varlogpods
          hostPath:
            path: /var/log/pods
        - name: varlibdockercontainers
          hostPath:
            path: /var/lib/docker/containers
---
apiVersion: beat.k8s.elastic.co/v1beta1
kind: Beat
metadata:
  name: filebeat-netflow
  namespace: monitoring
spec:
  type: filebeat
  version: 8.17.5
  elasticsearchRef:
    name: elasticsearch
  kibanaRef:
    name: kibana
  config:
    filebeat.modules:
      - module: netflow
        log:
          enabled: true
          var:
            netflow_host: 0.0.0.0
            netflow_port: 9995
    output.elasticsearch:
      hosts: ["elasticsearch.monitoring.svc.cluster.local:9200"]
      index: "netflow-%{[agent.version]}-%{+yyyy.MM.dd}"
    setup.template:
      name: 'netflow'
      pattern: 'netflow-*'
      enabled: true
  daemonSet:
    podTemplate:
      spec:
        hostNetwork: false # Allows to provide richer host metadata
        containers:
        - name: filebeat
          securityContext:
            runAsUser: 0
---
apiVersion: v1
kind: Service
metadata:
  name: filebeat-netflow
  namespace: monitoring
  labels:
    beat.k8s.elastic.co/name: filebeat-netflow
  annotations:
    tailscale.com/expose: "true"
    tailscale.com/hostname: "netflow"
    tailscale.com/tags: "tag:nfcapd"
spec:
  type: ClusterIP
  ports:
    - name: netflow
      port: 9995
      targetPort: 9995
      protocol: UDP
  selector:
    beat.k8s.elastic.co/name: filebeat-netflow
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: filebeat
  namespace: monitoring
rules:
- apiGroups: [""] # "" indicates the core API group
  resources:
  - namespaces
  - pods
  - nodes
  verbs:
  - get
  - watch
  - list
- apiGroups: ["apps"]
  resources:
  - replicasets
  verbs:
  - get
  - list
  - watch
- apiGroups: ["batch"]
  resources:
  - jobs
  verbs:
  - get
  - list
  - watch
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: filebeat
  namespace: monitoring
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: filebeat
  namespace: monitoring
subjects:
- kind: ServiceAccount
  name: filebeat
  namespace: default
roleRef:
  kind: ClusterRole
  name: filebeat
  apiGroup: rbac.authorization.k8s.io
