---
apiVersion: v1
kind: Service
metadata:
  name: http-files
  namespace: default
  annotations:
    tailscale.com/expose: "true"
    tailscale.com/hostname: "files"
    tailscale.com/tags: "tag:http"
spec:
  selector:
    app: http-files
  ports:
  - name: http
    port: 80
    targetPort: 80
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: http-files
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: http-files
  template:
    metadata:
      labels:
        app: http-files
    spec:
      containers:
      - name: http-files
        image: docker.io/heywoodlh/http-files:v2.10.2
        ports:
        - containerPort: 80
        volumeMounts:
        - name: http-files
          mountPath: /web
      volumes:
      - name: http-files
        hostPath:
          path: /opt/files

