---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nfcapd
  namespace: monitoring
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nfcapd
  template:
    metadata:
      labels:
        app: nfcapd
    spec:
      hostname: nfcapd
      containers:
      - name: nfcapd
        image: docker.io/heywoodlh/nfcapd:1.7.4
        ports:
        - name: nfcapd
          containerPort: 9995
          protocol: UDP
        volumeMounts:
          - mountPath: /flows
            name: flows
      volumes:
        - name: flows
          hostPath:
            path: /media/data-ssd/flows
            type: Directory
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: nfcapd
  name: nfcapd
  namespace: monitoring
  annotations:
    tailscale.com/expose: "true"
    tailscale.com/hostname: "nfcapd"
    tailscale.com/tags: "tag:nfcapd"
spec:
  ports:
  - name: web-ui
    port: 9995
    protocol: UDP
    targetPort: nfcapd
  selector:
    app: nfcapd
  type: ClusterIP
