---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: open-webui-data
  namespace: machine-learning
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      storage: 50Gi
---
apiVersion: v1
kind: Service
metadata:
  name: open-webui
  namespace: machine-learning
  annotations:
    tailscale.com/expose: "true"
    tailscale.com/hostname: "open-webui"
    tailscale.com/tags: "tag:http"
spec:
  type: NodePort
  selector:
    app: open-webui
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: open-webui-deployment
  namespace: machine-learning
spec:
  replicas: 1
  selector:
    matchLabels:
      app: open-webui
  template:
    metadata:
      labels:
        app: open-webui
    spec:
      containers:
      - name: open-webui
        image: ghcr.io/open-webui/open-webui:0.5.20
        ports:
        - containerPort: 8080
        resources:
          limits:
            cpu: 1000m
            memory: 1Gi
          requests:
            cpu: 500m
            memory: 500Mi
        volumeMounts:
        - name: open-webui-data
          mountPath: /app/backend/data
        env:
        - name: OLLAMA_API_BASE_URL
          value: "http://nix-nvidia.barn-banana.ts.net:11434/api"
        tty: true
      volumes:
      - name: open-webui-data
        persistentVolumeClaim:
          claimName: open-webui-data
#---
#apiVersion: v1
#kind: Service
#metadata:
#  name: ollama
#  namespace: machine-learning
#  labels:
#    app.kubernetes.io/name: ollama
#    app.kubernetes.io/instance: ollama
#  annotations:
#    tailscale.com/expose: "true"
#    tailscale.com/hostname: "ollama"
#    tailscale.com/tags: "tag:ollama"
#spec:
#  type: ClusterIP
#  ports:
#    - port: 11434
#      targetPort: ollama
#      protocol: TCP
#      name: ollama
#  selector:
#    app.kubernetes.io/name: ollama
#    app.kubernetes.io/instance: ollama
#---
#apiVersion: apps/v1
#kind: Deployment
#metadata:
#  name: ollama
#  namespace: machine-learning
#  labels:
#    app.kubernetes.io/name: ollama
#    app.kubernetes.io/instance: ollama
#spec:
#  replicas: 1
#  selector:
#    matchLabels:
#      app.kubernetes.io/name: ollama
#      app.kubernetes.io/instance: ollama
#  template:
#    metadata:
#      labels:
#        app.kubernetes.io/name: ollama
#        app.kubernetes.io/instance: ollama
#    spec:
#      securityContext:
#        {}
#      containers:
#        - name: ollama
#          securityContext:
#            {}
#          image: "docker.io/ollama/ollama:0.6.2"
#          imagePullPolicy: IfNotPresent
#          ports:
#            - name: ollama
#              containerPort: 11434
#              protocol: TCP
#          volumeMounts:
#            - name: ollama
#              mountPath: /root/.ollama
#          resources:
#            limits:
#              nvidia.com/gpu: 1
#          env:
#          - name: NVIDIA_VISIBLE_DEVICES
#            value: all
#          - name: NVIDIA_DRIVER_CAPABILITIES
#            value: all
#      volumes:
#      - name: ollama
#        hostPath:
#          path: /media/data-ssd/ollama
#          type: Directory
