---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: rustdesk-web-home
  namespace: default
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
---
apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  finalizers:
  - onepassword.com/finalizer.secret
  generation: 1
  name: rustdesk-web
  namespace: default
spec:
  itemPath: vaults/Kubernetes/items/onjhxpnzraw2orkjuymkfh6chy
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: rustdesk-web
  namespace: default
  labels:
    app.kubernetes.io/name: rustdesk-web
    app.kubernetes.io/instance: rustdesk-web
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: rustdesk-web
      app.kubernetes.io/instance: rustdesk-web
  template:
    metadata:
      labels:
        app.kubernetes.io/name: rustdesk-web
        app.kubernetes.io/instance: rustdesk-web
    spec:
      restartPolicy: Always
      containers:
        - name: rustdesk-web
          image: "docker.io/heywoodlh/rustdesk-web:1.3.8"
          imagePullPolicy: IfNotPresent
          volumeMounts:
          - name: rustdesk-web-home
            mountPath: /home/kasm-user
          env:
            - name: VNC_PW
              valueFrom:
                secretKeyRef:
                  name: rustdesk-web
                  key: password
          ports:
            - name: vnc
              containerPort: 6901
              protocol: TCP
      volumes:
      - name: rustdesk-web-home
        persistentVolumeClaim:
          claimName: rustdesk-web-home
---
apiVersion: v1
kind: Service
metadata:
  name: rustdesk-web
  namespace: default
  labels:
    app.kubernetes.io/name: rustdesk-web
    app.kubernetes.io/instance: rustdesk-web
  annotations:
    tailscale.com/expose: "true"
    tailscale.com/hostname: "rustdesk-web"
    tailscale.com/tags: "tag:http"
spec:
  type: ClusterIP
  ports:
    - port: 443
      targetPort: vnc
      protocol: TCP
      name: rustdesk-web
  selector:
    app.kubernetes.io/name: rustdesk-web
    app.kubernetes.io/instance: rustdesk-web
