# Tasks for individual hosts
---
- name: k8s-ceph host tasks
  when: ansible_hostname == 'k8s-ceph'
  block:
    - name: run k8s-ceph tasks
      include_tasks: ./roles/k8s-ceph.yml

- name: ssh-chat host tasks
  when: ansible_hostname == 'ssh-chat'
  block:
    - name: run ssh-chat tasks
      include_tasks: ./roles/ssh-chat.yml

- name: spencer-router host tasks
  when: ansible_hostname == 'spencer-router'
  block:
    - name: run spencer-router tasks
      include_tasks: ./hosts/spencer-router.yml

- name: cloud host tasks
  when: ansible_hostname == 'cloud'
  block:
    - name: run cloud tasks
      include_tasks: ./hosts/cloud.yml
