---
- name: install gnome and gdm
  ansible.builtin.apt:
    name: "{{ item }}"
    update_cache: yes
  with_items:
  - gdm3
  - gnome-control-center
  - gnome-shell
  - firefox
  - network-manager
  when: ansible_os_family == 'Debian'

- name: install gnome and gdm
  community.general.pacman:
    name: "{{ item }}"
    update_cache: yes
  with_items:
  - gdm
  - gnome-control-center
  - gnome-shell
  - gnome-terminal
  - firefox
  - networkmanager
  when: ansible_os_family == 'Archlinux'

- name: enable gdm
  ansible.builtin.systemd:
    name: gdm
    enabled: yes
  when: ansible_os_family == 'Archlinux'

- name: enable network manager
  ansible.builtin.systemd:
    name: NetworkManager.service
    enabled: yes
  when: ansible_os_family == 'Archlinux'

- name: Disable error reporting in Ubuntu
  ansible.builtin.replace:
    path: /etc/default/apport
    regexp: 'enabled=1'
    replace: 'enabled=0'
  when: ansible_distribution == 'Ubuntu'
  register: disable_apport

- name: Kill apport
  ansible.builtin.shell: "killall system-crash-notification"
  ignore_errors: true
