---
- name: create /etc/sudoers.d
  ansible.builtin.file:
    path: /etc/sudoers.d/
    state: directory

- name: "passwordless sudo for {{ username }}"
  ansible.builtin.lineinfile:
    path: "/etc/sudoers.d/{{ username }}"
    state: "{{ state }}"
    create: true
    regexp: "^{{ username }}"
    line: "{{ username }} ALL=(ALL) NOPASSWD: ALL"
    validate: 'visudo -cf %s'

