---
apiVersion: v1
kind: Service
metadata:
  name: actual
  namespace: @namespace@
  labels:
    app.kubernetes.io/name: actual
    app.kubernetes.io/instance: actual
  annotations:
    tailscale.com/expose: "true"
    tailscale.com/hostname: "actual"
    tailscale.com/tags: "tag:http"
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: http
      protocol: TCP
      name: actual
  selector:
    app.kubernetes.io/name: actual
    app.kubernetes.io/instance: actual
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: actual
  namespace: @namespace@
  labels:
    app.kubernetes.io/name: actual
    app.kubernetes.io/instance: actual
spec:
  replicas: @replicas@
  selector:
    matchLabels:
      app.kubernetes.io/name: actual
      app.kubernetes.io/instance: actual
  template:
    metadata:
      labels:
        app.kubernetes.io/name: actual
        app.kubernetes.io/instance: actual
    spec:
      securityContext:
        {}
      containers:
        - name: actual
          image: "@image@"
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 5006
              protocol: TCP
          env:
            - name: ACTUAL_PORT
              value: "5006"
          resources:
            {}
          volumeMounts:
            - name: datadir
              mountPath: /data
          livenessProbe:
            exec:
              command:
                - node
                - /app/src/scripts/health-check.js
            initialDelaySeconds: 15
            periodSeconds: 20
      volumes:
        - name: datadir
          hostPath:
            path: @hostfolder@

