---
apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  finalizers:
  - onepassword.com/finalizer.secret
  generation: 1
  name: cloudflared
  namespace: @namespace@
spec:
  itemPath: vaults/Kubernetes/items/vz6qpnbbus6btqwc4otx3bocqq
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cloudflared-cloudflare-tunnel
  namespace: @namespace@
  labels:
    app.kubernetes.io/name: cloudflared-tunnel
    app.kubernetes.io/instance: cloudflared
spec:
  replicas: @replicas@
  selector:
    matchLabels:
      app.kubernetes.io/name: cloudflare-tunnel
      app.kubernetes.io/instance: cloudflared
  template:
    metadata:
      labels:
        app.kubernetes.io/name: cloudflare-tunnel
        app.kubernetes.io/instance: cloudflared
    spec:
      restartPolicy: Always
      containers:
        - name: cloudflare-tunnel
          image: "@image@"
          imagePullPolicy: IfNotPresent
          env:
            - name: CLOUDFLARED_TOKEN
              valueFrom:
                secretKeyRef:
                  name: cloudflared
                  key: token
          args:
            - tunnel
            - --no-autoupdate
            - run
            - --token=$(CLOUDFLARED_TOKEN)
