---
apiVersion: v1
kind: ConfigMap
metadata:
  name: coredns
  namespace: @namespace@
  labels:
    app.kubernetes.io/instance: "coredns"
    app.kubernetes.io/name: coredns
data:
  Corefile: |-
    .:53 {
        errors
        health {
            lameduck 5s
        }
        ready
        kubernetes cluster.local in-addr.arpa ip6.arpa {
            pods insecure
            fallthrough in-addr.arpa ip6.arpa
            ttl 30
        }
        prometheus 0.0.0.0:9153
        forward . /etc/resolv.conf
        cache 30
        loop
        reload
        loadbalance
    }
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: coredns
  labels:
    app.kubernetes.io/instance: "coredns"
    app.kubernetes.io/name: coredns
rules:
- apiGroups:
  - ""
  resources:
  - endpoints
  - services
  - pods
  - namespaces
  verbs:
  - list
  - watch
- apiGroups:
  - discovery.k8s.io
  resources:
  - endpointslices
  verbs:
  - list
  - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: coredns
  labels:
    app.kubernetes.io/instance: "coredns"
    app.kubernetes.io/name: coredns
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: coredns
subjects:
- kind: ServiceAccount
  name: default
  namespace: @namespace@
---
apiVersion: v1
kind: Service
metadata:
  name: coredns-external
  namespace: @namespace@
  labels:
    app.kubernetes.io/instance: "coredns"
    app.kubernetes.io/name: coredns
  annotations:
    tailscale.com/expose: "true"
    tailscale.com/hostname: "coredns"
    tailscale.com/tags: "tag:kubedns"
spec:
  selector:
    app.kubernetes.io/instance: "coredns"
    app.kubernetes.io/name: coredns
  ports:
  - {"name":"udp-53","port":53,"protocol":"UDP","targetPort":53}
  - {"name":"tcp-53","port":53,"protocol":"TCP","targetPort":53}
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: coredns
  namespace: @namespace@
  labels:
    app.kubernetes.io/instance: "coredns"
    app.kubernetes.io/name: coredns
spec:
  replicas: @replicas@
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 25%
  selector:
    matchLabels:
      app.kubernetes.io/instance: "coredns"
      app.kubernetes.io/name: coredns
  template:
    metadata:
      labels:
        app.kubernetes.io/name: coredns
        app.kubernetes.io/instance: "coredns"
      annotations:
        checksum/config: 1faab9d928fd9f1452edafc933f0817d2d5443fa04feb628bb2d33c0ac60aee2
    spec:
      terminationGracePeriodSeconds: 30
      serviceAccountName: default
      containers:
      - name: "coredns"
        image: "@image@"
        imagePullPolicy: IfNotPresent
        args: [ "-conf", "/etc/coredns/Corefile" ]
        volumeMounts:
        - name: config-volume
          mountPath: /etc/coredns
        resources:
          limits:
            cpu: 100m
            memory: 128Mi
          requests:
            cpu: 100m
            memory: 128Mi
        ports:
        - {"containerPort":53,"name":"udp-53","protocol":"UDP"}
        - {"containerPort":53,"name":"tcp-53","protocol":"TCP"}
        - {"containerPort":9153,"name":"tcp-9153","protocol":"TCP"}

        livenessProbe:
          httpGet:
            path: /health
            port: 8080
            scheme: HTTP
          initialDelaySeconds: 60
          periodSeconds: 10
          timeoutSeconds: 5
          successThreshold: 1
          failureThreshold: 5
        readinessProbe:
          httpGet:
            path: /ready
            port: 8181
            scheme: HTTP
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          successThreshold: 1
          failureThreshold: 5
        securityContext:
          capabilities:
            add:
            - NET_BIND_SERVICE
      volumes:
        - name: config-volume
          configMap:
            name: coredns
            items:
            - key: Corefile
              path: Corefile
