---
apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  name: "dev-password"
  namespace: "@namespace@"
spec:
  itemPath: "vaults/Kubernetes/items/boofeqmvt6vmcdqsyzczhiwqre"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: dev-sshd-config
  namespace: @namespace@
data:
  sshd_config: |-
    Include /etc/ssh/sshd_config.d/*.conf
    ListenAddress 0.0.0.0
    KbdInteractiveAuthentication no
    UsePAM yes
    X11Forwarding yes
    PrintMotd no
    AcceptEnv LANG LC_*
    Subsystem       sftp    /usr/lib/openssh/sftp-server
    AuthorizedKeysCommand /keys.sh
    AuthorizedKeysCommandUser nobody
    PermitRootLogin prohibit-password
    HostKey /etc/ssh/host_keys/ssh_host_rsa_key
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: dev-keys
  namespace: @namespace@
data:
  keys.sh: |-
    #!/usr/bin/env bash
    curl -L --silent https://github.com/heywoodlh.keys
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: dev-gen-host-keys
  namespace: @namespace@
data:
  gen-host-keys.sh: |-
    #!/usr/bin/env bash
    [[ -e /etc/ssh/host_keys/ssh_host_rsa_key ]] || ssh-keygen -f /etc/ssh/host_keys/ssh_host_rsa_key -N '' -t rsa
    [[ -e /etc/ssh/host_keys/ssh_host_dsa_key ]] || ssh-keygen -f /etc/ssh/host_keys/ssh_host_dsa_key -N '' -t dsa
    # Overwrite host keys
    cp -rf /etc/ssh/host_keys/* /etc/ssh
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: dev-custom-fish
  namespace: @namespace@
data:
  custom.fish: |-
    function ssh-unlock
      op read 'op://Personal/rlt3q545cf5a4r4arhnb4h5qmi/private_key' | ssh-add -t 4h -
    end

    function k9s
      op-unlock
      $HOME/.nix-profile/bin/k9s $argv
    end

    function kubectl
      op-unlock
      $HOME/.nix-profile/bin/kubectl $argv
    end

---
apiVersion: v1
kind: Service
metadata:
  name: dev
  namespace: @namespace@
  labels:
    app.kubernetes.io/name: dev
    app.kubernetes.io/instance: dev
  annotations:
    tailscale.com/expose: "true"
    tailscale.com/hostname: "dev"
    tailscale.com/tags: "tag:http,tag:sshd"
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: ttyd
      protocol: TCP
      name: ttyd
    - port: 22
      targetPort: sshd
      protocol: TCP
      name: sshd
  selector:
    app.kubernetes.io/name: dev
    app.kubernetes.io/instance: dev
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: dev-nix
  namespace: @namespace@
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      storage: 128Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: dev-home
  namespace: @namespace@
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      storage: 128Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: dev-dind-storage
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      storage: 50Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: dev-dind-certs
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      storage: 100Mi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: dev-host-keys
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      storage: 100Mi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: dev
  namespace: @namespace@
  labels:
    app.kubernetes.io/name: dev
    app.kubernetes.io/instance: dev
spec:
  replicas: @replicas@
  selector:
    matchLabels:
      app.kubernetes.io/name: dev
      app.kubernetes.io/instance: dev
  template:
    metadata:
      labels:
        app.kubernetes.io/name: dev
        app.kubernetes.io/instance: dev
    spec:
      securityContext:
        {}
      containers:
        - name: dind
          image: docker.io/docker:dind
          ports:
            - name: dind-con-port
              containerPort: 2376
              protocol: TCP
          volumeMounts:
            - name: dev-dind-certs
              mountPath: /certs/client
            - name: dev-dind-storage
              mountPath: /var/lib/docker
          tty: true
          securityContext:
            privileged: true
        - name: dev
          image: "@image@"
          command:
            - "bash"
            - "-c"
          args: [ "/gen-host-keys.sh && /usr/bin/supervisord -c /etc/supervisor/conf.d/supervisord.conf" ]
          imagePullPolicy: IfNotPresent
          ports:
            - name: ttyd
              containerPort: 80
              protocol: TCP
            - name: sshd
              containerPort: 22
              protocol: TCP
          resources:
            {}
          volumeMounts:
            - name: dev-nix
              mountPath: /nix
            - name: dev-home
              mountPath: /home/heywoodlh
            - name: dev-dind-certs
              mountPath: /certs
            - name: dev-sshd-config
              mountPath: /etc/ssh/sshd_config.d/sshd.conf
              subPath: sshd.conf
            - name: dev-keys
              mountPath: /keys.sh
              subPath: keys.sh
            - name: dev-gen-host-keys
              mountPath: /gen-host-keys.sh
              subPath: gen-host-keys.sh
            - name: dev-custom-fish
              mountPath: /home/heywoodlh/.config/fish/custom.fish
              subPath: custom.fish
            - name: dev-host-keys
              mountPath: /etc/ssh/host_keys
          env:
            - name: DOCKER_TLS_CERTDIR
              value: '/certs'
            - name: DOCKER_CERT_PATH
              value: '/certs'
            - name: DOCKER_HOST
              value: "tcp://localhost:2376"
            - name: DOCKER_TLS_VERIFY
              value: "1"
            - name: TTYD_USER
              valueFrom:
                secretKeyRef:
                  name: dev-password
                  key: username
            - name: TTYD_PASS
              valueFrom:
                secretKeyRef:
                  name: dev-password
                  key: password
      volumes:
        - name: dev-dind-certs
          persistentVolumeClaim:
            claimName: dev-dind-certs
        - name: dev-dind-storage
          persistentVolumeClaim:
            claimName: dev-dind-storage
        - name: dev-nix
          persistentVolumeClaim:
            claimName: dev-nix
        - name: dev-home
          persistentVolumeClaim:
            claimName: dev-home
        - name: dev-sshd-config
          configMap:
            name: dev-sshd-config
        - name: dev-custom-fish
          configMap:
            name: dev-custom-fish
        - name: dev-keys
          configMap:
            name: dev-keys
            defaultMode: 0777
        - name: dev-gen-host-keys
          configMap:
            name: dev-gen-host-keys
            defaultMode: 0777
        - name: dev-host-keys
          persistentVolumeClaim:
            claimName: dev-host-keys


