---
kind: ConfigMap
metadata:
  name: coredns
  namespace: kube-system
apiVersion: v1
data:
  Corefile: |
    .:53 {
        errors
        health
        ready
        kubernetes cluster.local in-addr.arpa ip6.arpa {
          pods insecure
          fallthrough in-addr.arpa ip6.arpa
        }
        hosts /etc/coredns/NodeHosts {
          ttl 60
          reload 15s
          fallthrough
        }
        prometheus :9153
        forward . 45.90.28.89:53
        cache 30
        loop
        reload
        loadbalance
    }
    @tailnet@:53 {
        forward . 10.43.0.15
    }
  NodeHosts: |
    192.168.1.22 nix-nvidia
#---
#apiVersion: v1
#kind: ConfigMap
#metadata:
#  name: coredns-custom # has to be named this
#  namespace: kube-system
#data:
#  @tailnet@.server: |
#    @tailnet@ {
#      forward . 100.100.100.100
#    }
