---
apiVersion: v1
kind: Service
metadata:
  name: metube
  namespace: @namespace@
  labels:
    app.kubernetes.io/name: metube
    app.kubernetes.io/instance: metube
  annotations:
    tailscale.com/expose: "true"
    tailscale.com/hostname: "metube"
    tailscale.com/tags: "tag:http"
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: http
  selector:
    app.kubernetes.io/name: metube
    app.kubernetes.io/instance: metube
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv0003
spec:
  capacity:
    storage: 5Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Recycle
  storageClassName: home-media
  mountOptions:
    - nfsvers=4.1
    - nolock
  nfs:
    path: /tmp
    server: 172.17.0.2
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: metube
  namespace: @namespace@
  labels:
    app.kubernetes.io/name: metube
    app.kubernetes.io/instance: metube
spec:
  strategy:
    type: Recreate
  replicas: @replicas@
  selector:
    matchLabels:
      app.kubernetes.io/name: metube
      app.kubernetes.io/instance: metube
  template:
    metadata:
      labels:
        app.kubernetes.io/name: metube
        app.kubernetes.io/instance: metube
    spec:
      containers:
        - name: metube
          image: "@image@"
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 8081
              protocol: TCP
          env:
            - name: UID
              value: "995"
            - name: GID
              value: "995"
            - name: DEFAULT_THEME
              value: "dark"
          livenessProbe:
            tcpSocket:
              port: http
          readinessProbe:
            tcpSocket:
              port: http
          volumeMounts:
            - mountPath: /downloads
              subPath: "disk2/videos"
              name: videos
          resources: {}
      volumes:
      - name: videos
        nfs:
          server: 100.69.115.100
          path: /media/home-media
