---
apiVersion: v1
kind: Service
metadata:
  name: ollama-lb
  namespace: @namespace@
  labels:
    app.kubernetes.io/name: ollama-lb
    app.kubernetes.io/instance: ollama-lb
  annotations:
    tailscale.com/expose: "true"
    tailscale.com/hostname: "ollama"
    tailscale.com/tags: "tag:ollama"
spec:
  type: ClusterIP
  ports:
    - port: 11434
      targetPort: ollama
      protocol: TCP
      name: ollama
  selector:
    app.kubernetes.io/name: ollama-lb
    app.kubernetes.io/instance: ollama-lb
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ollama-lb
  namespace: @namespace@
  labels:
    app.kubernetes.io/name: ollama-lb
    app.kubernetes.io/instance: ollama-lb
spec:
  replicas: @replicas@
  selector:
    matchLabels:
      app.kubernetes.io/name: ollama-lb
      app.kubernetes.io/instance: ollama-lb
  template:
    metadata:
      labels:
        app.kubernetes.io/name: ollama-lb
        app.kubernetes.io/instance: ollama-lb
    spec:
      securityContext:
        {}
      containers:
        - name: ollama-lb
          securityContext:
            {}
          image: "@image@"
          command:
            - "ollama_load_balancer"
          args:
            - "--server=100.83.100.5:11434=nvidia"
            - "--server=100.108.77.60:11434=mac"
          imagePullPolicy: IfNotPresent
          ports:
            - name: ollama
              containerPort: 11434
              protocol: TCP
          resources:
            {}
