---
apiVersion: v1
kind: Namespace
metadata:
  name: @namespace@
---
apiVersion: v1
kind: Service
metadata:
  name: open-webui
  namespace: @namespace@
  annotations:
    tailscale.com/expose: "true"
    tailscale.com/hostname: "open-webui"
    tailscale.com/tags: "tag:http"
spec:
  type: NodePort
  selector:
    app: open-webui
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: open-webui-deployment
  namespace: @namespace@
spec:
  replicas: 1
  selector:
    matchLabels:
      app: open-webui
  template:
    metadata:
      labels:
        app: open-webui
    spec:
      containers:
      - name: open-webui
        image: @webui_image@
        ports:
        - containerPort: 8080
        resources:
          limits:
            cpu: 1000m
            memory: 1Gi
          requests:
            cpu: 500m
            memory: 500Mi
        volumeMounts:
        - name: open-webui-data
          mountPath: /app/backend/data
        env:
        - name: OLLAMA_BASE_URL
          value: "http://ollama.default.svc.cluster.local:11434"
        tty: true
      volumes:
      - name: open-webui-data
        hostPath:
          path: @hostfolder@/data
          type: Directory
