---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: rustdesk-web-home
  namespace: @namespace@
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: rustdesk-sudo-conf
  namespace: @namespace@
data:
  sudoers: |
    kasm-user ALL=(ALL) NOPASSWD: ALL # to change password for initial rustdesk config: `sudo passwd kasm-user`
---
apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  finalizers:
  - onepassword.com/finalizer.secret
  generation: 1
  name: rustdesk-web
  namespace: @namespace@
spec:
  itemPath: vaults/Kubernetes/items/onjhxpnzraw2orkjuymkfh6chy
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: rustdesk-web
  namespace: @namespace@
  labels:
    app.kubernetes.io/name: rustdesk-web
    app.kubernetes.io/instance: rustdesk-web
spec:
  replicas: @replicas@
  selector:
    matchLabels:
      app.kubernetes.io/name: rustdesk-web
      app.kubernetes.io/instance: rustdesk-web
  template:
    metadata:
      labels:
        app.kubernetes.io/name: rustdesk-web
        app.kubernetes.io/instance: rustdesk-web
    spec:
      restartPolicy: Always
      containers:
        - name: rustdesk-web
          image: "@image@"
          imagePullPolicy: IfNotPresent
          volumeMounts:
          - name: rustdesk-web-home
            mountPath: /home/kasm-user
          - name: rustdesk-sudo-conf
            mountPath: /etc/sudoers.d/kasm-user
            subPath: kasm-user
          env:
            - name: VNC_PW
              valueFrom:
                secretKeyRef:
                  name: rustdesk-web
                  key: password
          ports:
            - name: vnc
              containerPort: 6901
              protocol: TCP
      volumes:
        - name: rustdesk-web-home
          persistentVolumeClaim:
            claimName: rustdesk-web-home
        - name: rustdesk-sudo-conf
          configMap:
            name: rustdesk-sudo-conf
            items:
            - key: sudoers
              path: kasm-user
---
apiVersion: v1
kind: Service
metadata:
  name: rustdesk-web
  namespace: @namespace@
  labels:
    app.kubernetes.io/name: rustdesk-web
    app.kubernetes.io/instance: rustdesk-web
  annotations:
    tailscale.com/expose: "true"
    tailscale.com/hostname: "rustdesk-web"
    tailscale.com/tags: "tag:http"
spec:
  type: ClusterIP
  ports:
    - port: 443
      targetPort: vnc
      protocol: TCP
      name: rustdesk-web
  selector:
    app.kubernetes.io/name: rustdesk-web
    app.kubernetes.io/instance: rustdesk-web
