---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: wazuh-manager-master
  namespace: wazuh
spec:
  selector:
    matchLabels:
      node-type: wazuh
  template:
    metadata:
      labels:
        node-type: wazuh
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: wazuh-manager-worker
  namespace: wazuh
spec:
  selector:
    matchLabels:
      node-type: wazuh
  template:
    metadata:
      labels:
        node-type: wazuh
