name: test-ansible-playbooks

on:
  workflow_dispatch:
  push:
    paths:
      - ansible/**

jobs:
  test-ansible-playbooks:
    name: Test ansible playbooks with Docker
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Build containers and test
        run: |
          ./ansible/test.sh

