name: build-all-flakes

on:
  workflow_dispatch:

jobs:
  build-flakes:
    name: Build all flakes
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v5

    - name: Login to Tailnet
      uses: tailscale/github-action@v3
      with:
        oauth-client-id: ${{ secrets.TS_OAUTH_CLIENT_ID }}
        oauth-secret: ${{ secrets.TS_OAUTH_SECRET }}
        tags: tag:ci

    - name: Install Nix
      uses: DeterminateSystems/nix-installer-action@main
      with:
        determinate: true

    - name: Set up binary cache
      env:
        ATTIC_PUBKEY: ${{ secrets.ATTIC_LINUX_PUBKEY }}
        ATTIC_CACHE: "http://attic/nixos"
      run: |
        sudo tee -a /etc/nix/nix.conf > /dev/null <<EOF
        extra-substituters = $ATTIC_CACHE
        extra-trusted-public-keys = $ATTIC_PUBKEY
        EOF

    - name: Update sub-flakes
      run: |
        nix flake update ./fish
        nix flake update ./vim
        nix flake update ./git
        nix flake update ./vscode
        nix flake update ./wezterm
        nix flake update ./st
        nix flake update ./jetporch
        nix flake update .

    - name: If scheduled or manually triggered, add updated flake.lock if changed, commit and push
      uses: EndBug/add-and-commit@v9
      with:
        add: './'
        author_name: 'github-actions'
        author_email: 'github-actions@github.com'
