name: kubernetes cd

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * 2"
  push:
    branches:
      - main
    paths:
      - kube/**
      - '!kube/**.md'
      - .github/workflows/kubernetes-cd.yaml

jobs:
  deploy-services:
    name: Check and apply all deployments
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Install Nix
      uses: cachix/install-nix-action@v31

    - name: Update manifests
      run: |
        ./kube/render.sh

    - name: Commit changes
      uses: stefanzweifel/git-auto-commit-action@v5
      if: github.ref == 'refs/heads/main'
      with:
        commit_message: "GitHub Action automated Kubernetes update"
        file_pattern: 'kube/manifests/*.yaml'
